src/Entity/Module.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ModuleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ModuleRepository::class)]
class Module
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $nbre_sceance = null;

    #[ORM\ManyToOne(inversedBy: 'modules')]
    private ?typemodule $Type_module_id = null;

    #[ORM\ManyToOne(inversedBy: 'module_id')]
    private ?ModuleCoach $module_id = null;

    #[ORM\OneToMany(mappedBy: 'id_module', targetEntity: Session::class)]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNbreSceance(): ?int
    {
        return $this->nbre_sceance;
    }

    public function setNbreSceance(?int $nbre_sceance): self
    {
        $this->nbre_sceance = $nbre_sceance;

        return $this;
    }


    public function setTypeModuleId(?typemodule $Type_module_id): self
    {
        $this->Type_module_id = $Type_module_id;

        return $this;
    }

    public function getModuleId(): ?ModuleCoach
    {
        return $this->module_id;
    }

    public function setModuleId(?ModuleCoach $module_id): self
    {
        $this->module_id = $module_id;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setIdModule($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getIdModule() === $this) {
                $session->setIdModule(null);
            }
        }

        return $this;
    }






}

src/Form/ModuleType.php
<?php

namespace App\Form;

use App\Entity\Module;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ModuleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('nbre_sceance')
            ->add('Type_module_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Module::class,
        ]);
    }
}

templates/module/_delete_form.html.twig
<form method="post" action="{{ path('app_module_delete', {'id': module.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ module.id) }}">
    <button class="btn">Delete</button>
</form>

templates/module/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/module/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Module{% endblock %}

{% block body %}
    <h1>Edit Module</h1>

    {{ include('module/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_module_index') }}">back to list</a>

    {{ include('module/_delete_form.html.twig') }}
{% endblock %}

templates/module/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Module index{% endblock %}

{% block body %}
    <h1>Module index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Nbre_sceance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for module in modules %}
            <tr>
                <td>{{ module.id }}</td>
                <td>{{ module.name }}</td>
                <td>{{ module.nbreSceance }}</td>
                <td>
                    <a href="{{ path('app_module_show', {'id': module.id}) }}">show</a>
                    <a href="{{ path('app_module_edit', {'id': module.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_module_new') }}">Create new</a>
{% endblock %}

templates/module/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Module{% endblock %}

{% block body %}
    <h1>Create new Module</h1>

    {{ include('module/_form.html.twig') }}

    <a href="{{ path('app_module_index') }}">back to list</a>
{% endblock %}

templates/module/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Module{% endblock %}

{% block body %}
    <h1>Module</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ module.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ module.name }}</td>
            </tr>
            <tr>
                <th>Nbre_sceance</th>
                <td>{{ module.nbreSceance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_module_index') }}">back to list</a>

    <a href="{{ path('app_module_edit', {'id': module.id}) }}">edit</a>

    {{ include('module/_delete_form.html.twig') }}
{% endblock %}